// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vizxhaympbmstrycemeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpenhoYXltcGJtc3RyeWNlbWVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTMwNDcsImV4cCI6MjA2MDYyOTA0N30.2OGJpn8OewHtn9f7XJlbyUTsX8l5XOYML2hGv11IOnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);